name: Integration Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  spin-up-cluster:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install openjdk-8-jre -y
          wget -O tlp-cluster.deb https://bintray.com/thelastpickle/tlp-tools-deb/download_file?file_path=tlp-cluster_0.5_all.deb
          sudo dpkg -i tlp-cluster.deb
          mkdir -p .tlp-cluster/profiles/default

          sudo apt-get install     apt-transport-https     ca-certificates     curl     gnupg-agent     software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
          sudo usermod -aG docker ${USER}
    - name: Configure tlp-cluster
      env:
        TLP_CLUSTER_KEY: ${{ secrets.TLP_CLUSTER_KEY }}
      run: |
          set -e
          if [[ -n "${TLP_CLUSTER_KEY}" ]];
          then
            mv secret.pem .tlp-cluster/profiles/default/
            echo '${{ secrets.TLP_CLUSTER_SETTINGS }}' > .tlp-cluster/profiles/default/settings.yaml
            echo '${TLP_CLUSTER_KEY}' > .tlp-cluster/profiles/default/secret.pem
            home_dir=$(pwd)
            sed -i 's,~,'"${home_dir}"',' ./settings.yaml 
          fi
    - name: Spin up cluster
      run: |
          tlp-cluster init DS DSI-58 "Integration tests for the DS diagnostic toolkit"
    - name: Tear down
      if: ${{ always() }}
      run: |
        tlp-cluster down --auto-approve
